export default [
  {
    id: 1,
    num: '001',
    name: 'Bulbasaur',
    img: 'http://www.serebii.net/pokemongo/pokemon/001.png',
  },
  {
    id: 2,
    num: '002',
    name: 'Wartortle',
    img: 'http://www.serebii.net/pokemongo/pokemon/008.png',
  },
  {
    id: 3,
    num: '003',
    name: 'Charmeleon',
    img: 'http://www.serebii.net/pokemongo/pokemon/005.png',
  },
  {
    id: 4,
    num: '004',
    name: 'Charizard',
    img: 'http://www.serebii.net/pokemongo/pokemon/006.png',
  },
  {
    id: 5,
    num: '005',
    name: 'Squirtle',
    img: 'http://www.serebii.net/pokemongo/pokemon/007.png',
  },
  {
    id: 6,
    num: '006',
    name: 'Raichu',
    img: 'http://www.serebii.net/pokemongo/pokemon/026.png',
  },
  {
    id: 7,
    num: '007',
    name: 'Wigglytuff',
    img: 'http://www.serebii.net/pokemongo/pokemon/040.png',
  },
  {
    id: 8,
    num: '008',
    name: 'Mewtwo',
    img: 'http://www.serebii.net/pokemongo/pokemon/150.png',
  },
  {
    id: 9,
    num: '009',
    name: 'Mew',
    img: 'http://www.serebii.net/pokemongo/pokemon/151.png',
  },
  {
    id: 10,
    num: '010',
    name: 'Butterfree',
    img: 'http://www.serebii.net/pokemongo/pokemon/012.png',
  },
  {
    id: 11,
    num: '011',
    name: 'Pidgey',
    img: 'http://www.serebii.net/pokemongo/pokemon/016.png',
  },
  {
    id: 12,
    num: '012',
    name: 'Pikachu',
    img: 'http://www.serebii.net/pokemongo/pokemon/025.png',
  },
  {
    id: 13,
    num: '013',
    name: 'Bulbasaur',
    img: 'http://www.serebii.net/pokemongo/pokemon/001.png',
  },
  {
    id: 14,
    num: '014',
    name: 'Wartortle',
    img: 'http://www.serebii.net/pokemongo/pokemon/008.png',
  },
  {
    id: 15,
    num: '015',
    name: 'Charmeleon',
    img: 'http://www.serebii.net/pokemongo/pokemon/005.png',
  },
  {
    id: 16,
    num: '016',
    name: 'Charizard',
    img: 'http://www.serebii.net/pokemongo/pokemon/006.png',
  },
  {
    id: 17,
    num: '017',
    name: 'Squirtle',
    img: 'http://www.serebii.net/pokemongo/pokemon/007.png',
  },
  {
    id: 18,
    num: '018',
    name: 'Raichu',
    img: 'http://www.serebii.net/pokemongo/pokemon/026.png',
  },
  {
    id: 19,
    num: '019',
    name: 'Wigglytuff',
    img: 'http://www.serebii.net/pokemongo/pokemon/040.png',
  },
  {
    id: 20,
    num: '020',
    name: 'Mewtwo',
    img: 'http://www.serebii.net/pokemongo/pokemon/150.png',
  },
  {
    id: 21,
    num: '021',
    name: 'Mew',
    img: 'http://www.serebii.net/pokemongo/pokemon/151.png',
  },
  {
    id: 22,
    num: '022',
    name: 'Butterfree',
    img: 'http://www.serebii.net/pokemongo/pokemon/012.png',
  },
  {
    id: 23,
    num: '023',
    name: 'Pidgey',
    img: 'http://www.serebii.net/pokemongo/pokemon/016.png',
  },
  {
    id: 24,
    num: '024',
    name: 'Pikachu',
    img: 'http://www.serebii.net/pokemongo/pokemon/025.png',
  }
]